"""empty message

Revision ID: 10485cfe8ec5
Revises: b43a2631f611
Create Date: 2022-01-24 23:29:18.487688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10485cfe8ec5'
down_revision = 'b43a2631f611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupon', type_='foreignkey')
    op.drop_column('coupon', 'valid_till')
    op.drop_column('coupon', 'date')
    op.drop_column('coupon', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('uid', sa.INTEGER(), nullable=True))
    op.add_column('coupon', sa.Column('date', sa.DATE(), nullable=True))
    op.add_column('coupon', sa.Column('valid_till', sa.DATE(), nullable=True))
    op.create_foreign_key(None, 'coupon', 'user', ['uid'], ['uid'])
    # ### end Alembic commands ###
