"""empty message

Revision ID: 332a73ef9be1
Revises: 4f6d465efec3
Create Date: 2022-01-24 12:23:49.880832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332a73ef9be1'
down_revision = '4f6d465efec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('coupon_id', sa.String(), nullable=True),
    sa.Column('percentage', sa.String(), nullable=True),
    sa.Column('valid_till', sa.Date(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coupon_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupon')
    # ### end Alembic commands ###
