"""empty message

Revision ID: b43a2631f611
Revises: 332a73ef9be1
Create Date: 2022-01-24 12:26:40.591986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43a2631f611'
down_revision = '332a73ef9be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('coupon_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'coupon_id')
    # ### end Alembic commands ###
